language: node_js
node_js:
- '6'
script: NODE_ENV=test mocha test/index_tests
deploy:
  provider: heroku
  app: daniel-mocha-tester
  api_key:
    secure: BkA+jjgfS5sfBOCOPXf3aAEx7st73BwonIfrTtIyOfjlAsoIU8dHZ4AEGUfw8lxHIhW+dHHYY0swLNG3noWBS0XKpP+Cfjx60dAvmDWKpKvfUcH8+daKXy3w9w3Ifkn7dMNymB0X64qbXBEwxmZLmTm8lk6qvZh4/Bjqcs9w0mhiLpMteLtwqpsWOPQVz1/xkt4zUlwSLS02ZBRR8X8oS6tpgEYqu/Y4vL3ELyyaLqlK3aF2dRV76rirh+5KGRRMhIjtnDXVcZGX/FP3E/tUDyAwjOBeoS07/6CsHFfLZV0DI0RzeawlqExyY0nSueEDyeKHtYwuplUM0on3Vg1AXZvDXQNJYnBYHPCYu0w7AOO8D3h5wCrrhgh/z5c8Qfqp6xYhiNzZnD4h2e4c/hlWJGHCsvdZl6hUaY0ARWfp0sM2lGwXp7YyN8/PDu7uBYd7wO1sLBzKMPuhIoIk6PHQYKGtsc+8KxagIETgZrb9FJ1vh93A2ELGRRs2anrPtqTe1MZZ2lheZiHuodDtDX3MJ1M7ymciranaxJkAsTHB32qpwHe1b+1K3nwVm2cQONh40fGnGDlRInHcuXfVN9ePDHxzylOA1/hX61/IoMYbkRJEsrYsZH/8X9RC4TaxDbHobLfIo40ru2OnJWh5aHloruo1Sh804QfGZSAXdcLajtc=
