language: node_js
node_js:
- '6'
script: NODE_ENV=test mocha test/index_tests
deploy:
  api_key:
    secure: dv9Eb7EOzD/BtOGBdtwSWKdnZLaXKkh/ZJaND5GiYMMIUr6PqE3DOrqGzVPZMVhDEgrLusiSJOei92i45MRVOZTXw6uG3Rlec6X0WE8qVqajAUdO0WJoQ2OZtQ+Z1u6QX1Wzu782qMmeXnz/YEh63CGsyedc+TNmUw24ZFamUL+kNBDH5ry2HJTZHqrAPiw8zDF9t7IEJ1UT55I/PpTfexSbXIpYIce8Nx8TkWEvzt81exKF2xcWonvyNhyHpQoDz13lMHcoE0zWxpFz7fAyNVju6EEMaGvAWnksDSITxklvvr9nkPBOu6GYSZ+9+T8G/gvOBweUWO1lgh61GmhxaPFhJ7lzI6Y+B+TWxoP7mUUO2CeONH8Tz3+ad0U5oeOBd9IErCnmzUUVL8iGLvVvOhhSZhw6wDDYcZcL5+FBKq47l6p+P4QF0c3n4H/py0Z021UNWKJ6rOWD9iGn6aNgMDnDTWJu7PNgocMxvIH4nv8pxp33Kf4cBCAv0Ar/W+JHx6AdaVo+AvI6rm1LwBEeClYapQuQRWoG1Xru6IUjUpSpDz73m5XD/LRkZGtOmgLSJE2pYYOMeaSzFN0vwBXkqhowAXsEKKQZ1R7DD/kO0AztOKj02Pgi0CykWzvGPZY1UPUKXn3XUUzCxhzlAFaKyR6SdVO5OUCOKnOmMpXIoNk=
